using System;
using System.Collections.Generic;

namespace iCloud.Apis.Auth.Responses
{
    /// <summary>
    /// Authorization Code response for the redirect URL after end user grants or denies authorization as specified
    /// in http://tools.ietf.org/html/rfc6749#section-4.1.2.
    /// <para>
    /// Check that <see cref="P:ICloud.Apis.Auth.OAuth2.Responses.AuthorizationCodeResponseUrl.Code" /> is not <c>null</c> or empty to verify the end-user granted authorization.
    /// </para>
    /// </summary>
    public class AuthorizationCodeResponseUrl 
    {
        /// <summary>Gets or sets the authorization code generated by the authorization server.</summary>
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the state parameter matching the state parameter in the authorization request.
        /// </summary>
        public string State { get; set; }

        /// <summary>
        /// Gets or sets the error code (e.g. "invalid_request", "unauthorized_client", "access_denied",
        /// "unsupported_response_type", "invalid_scope", "server_error", "temporarily_unavailable") as specified in
        /// http://tools.ietf.org/html/rfc6749#section-4.1.2.1.
        /// </summary>
        public string Error { get; set; }

        /// <summary>
        /// Gets or sets the human-readable text which provides additional information used to assist the client
        /// developer in understanding the error occurred.
        /// </summary>
        public string ErrorDescription { get; set; }

        /// <summary>
        /// Gets or sets the URI identifying a human-readable web page with provides information about the error.
        /// </summary>
        public string ErrorUri { get; set; }

        /// <summary>Constructs a new authorization code response URL from the specified dictionary.</summary>
        public AuthorizationCodeResponseUrl(IDictionary<string, string> queryString)
        {
            this.InitFromDictionary(queryString);
        }

        /// <summary>Constructs a new authorization code response URL from the specified query string.</summary>
        public AuthorizationCodeResponseUrl(string query)
        {
            string[] strArray1 = query.Split('&');
            Dictionary<string, string> dictionary = new Dictionary<string, string>();
            foreach (string str in strArray1)
            {
                char[] chArray = new char[1] { '=' };
                string[] strArray2 = str.Split(chArray);
                dictionary[strArray2[0]] = strArray2[1];
            }
            this.InitFromDictionary(dictionary);
        }

        /// <summary>Initializes this instance from the input dictionary.</summary>
        private void InitFromDictionary(IDictionary<string, string> queryString)
        {
            IDictionary<string, Action<string>> dictionary = new Dictionary<string, Action<string>>
            {
                ["code"] = v => this.Code = v,
                ["state"] = v => this.State = v,
                ["error"] = v => this.Error = v,
                ["error_description"] = v => this.ErrorDescription = v,
                ["error_uri"] = v => this.ErrorUri = v
            };
            foreach (KeyValuePair<string, string> keyValuePair in queryString)
            {
                if (dictionary.TryGetValue(keyValuePair.Key, out Action<string> action))
                    action(keyValuePair.Value);
            }
        }

        /// <summary>Constructs a new empty authorization code response URL.</summary>
        public AuthorizationCodeResponseUrl()
        {
        }
    }
}
